# Generated by Django 5.2.7 on 2025-10-26 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Banco')),
                ('account_type', models.CharField(choices=[('checking', 'Conta Corrente'), ('savings', 'Poupança'), ('wallet', 'Carteira')], default='checking', max_length=20, verbose_name='Tipo de Conta')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_ac_user_id_0bca0f_idx')],
            },
        ),
    ]
