# Generated by Django 5.2.7 on 2025-10-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_balance'),
        ('categories', '0002_category_categories__user_id_f0c68e_idx'),
        ('transactions', '0002_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', '-transaction_date'], name='transaction_account_984d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'transaction_type'], name='transaction_account_6aecfc_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', 'transaction_type'], name='transaction_categor_d0eb4b_idx'),
        ),
    ]
