# Generated by Django 5.2.7 on 2025-10-29 00:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'category_type'], name='categories__user_id_f0c68e_idx'),
        ),
    ]
